<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>246f0fbe-b299-416d-9aeb-b9058ed01bdd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="9.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiniErp.Application\MiniErp.Application.csproj" />
    <ProjectReference Include="..\MiniErp.Infrastructure\MiniErp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
